config/routes.rb
Rails.application.routes.draw do
  
  resources :store_to_visits
  resources :products
  resources :comments
  root 'dashboard#home'
  match '/home', to: 'dashboard#home', via: 'get'
  get 'stores/new'

  get 'stores/create'
  devise_for :users

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def home
    @title = 'home'
    @stores = Store.all
    @store_options = @stores.map{ |u| [ u.name, u.id ] }
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_comments.html.erb
<div class="container" style="width: 100%; margin-top: 5%;">
	<table id="comments" class="table table-striped" style="width: inherit">
		<thead>
			<tr>
				<th></th>
				<th>Content</th>
				<th>User</th>
				<th>Store</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
		</thead>
		<tbody>
			<% @comments = Comment.all %>
			<% @comments.each do |comment| %>
			<% commentUser = User.find(comment.user_id) %>
			<% store = Store.find(comment.store_id) %>
			<tr>
				<td></td>
				<td><%= comment.content %></td>
				<td><%= commentUser.email %></td>
				<td><%= store.name %></td>
				<% if commentUser.id == current_user.id %>
				<td align="center"> <%= link_to(edit_comment_path(comment), 'data-target' => "#myCommentModal}",
				'data-toggle' => 'modal') do  %> <i class="fa fa-pencil fa-2x center"></i> <% end %> </td>
				<div class="modal fade" id='<%= "myCommentModal" %>' tabindex="-1" role="dialog"
				aria-labelledby="myModalLabel" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
									&times;
								</button>
								<h4 class="modal-title" id="myModalLabel" align="left">Edit Comment</h4>
							</div>
							<% @comment = Comment.find(comment.id) %>
							<%= form_for @comment do |f| %>
							<div class="modal-body">
								<%= render partial: 'comments/edit', :locals => { f: f } %>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default" data-dismiss="modal">
									Cancel
								</button>
								<%= f.submit "Save Comment", class: "btn btn-primary" %>
							</div>
							<% end %>
						</div><!-- /.modal-content -->
					</div><!-- /.modal-dialog -->
				</div><!-- /.modal -->
				<td align="center"> <%= link_to(@comment, method: :delete, data: {confirm: 'Are you sure?'}) do  %> <i class="fa fa-trash fa-2x center"></i> <% end %> </td>
				<% else %>
				<td><strong>Created On: </strong> <%= comment.created_at.strftime("%b. %d, %Y") %> </td>
				<td><strong>Last Modified: </strong> <%= comment.updated_at.strftime("%b. %d, %Y") %> </td>
				<% end %>
			</tr>
			<% end %>

		</tbody>

	</table>
</div>
<script>
	$(document).ready(function() {
		var t = $('#comments').DataTable({
			"columnDefs" : [{
				"searchable" : false,
				"orderable" : false,
				"targets" : 0
			}],
			"order" : [[1, 'asc']]
		});

		t.on('order.dt search.dt', function() {
			t.column(0, {
				search : 'applied',
				order : 'applied'
			}).nodes().each(function(cell, i) {
				cell.innerHTML = i + 1;
			});
		}).draw();
	}); 
</script>

app/views/dashboard/_itinerary.html.erb
<div class="container" style="width: 100%; margin-top: 5%;">
	<table id="itinerary" class="table table-striped" style="width: inherit">
		<thead>
			<tr>
				<th></th>
				<th>Store</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
		</thead>
		<tbody>
			<% @storesToVisit = StoreToVisit.all %>

			<% @storesToVisit.each do |storeToVisit| %>
			<% storeToVisitUser = User.find(storeToVisit.user_id) %>
			<% store = Store.find(storeToVisit.store_id) %>
			<% if storeToVisitUser.id == current_user.id %>
			<tr>
				<td></td>
				<td><%= store.name %></td>
				<td align="center"> <%= link_to(edit_store_to_visit_path(storeToVisit), 'data-target' => "#myStoreToVisit",
				'data-toggle' => 'modal') do  %> <i class="fa fa-pencil fa-2x center"></i> <% end %> </td>
				<div class="modal fade" id='<%= "myStoreToVisit" %>' tabindex="-1" role="dialog"
				aria-labelledby="myModalLabel" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
									&times;
								</button>
								<h4 class="modal-title" id="myModalLabel" align="left">Edit Store To Visit</h4>
							</div>
							<% @storeToVisit = StoreToVisit.find(storeToVisit.id) %>
							<%= form_for @storeToVisit do |f| %>
							<div class="modal-body">
								<%= render partial: 'store_to_visits/edit', :locals => { f: f } %>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default" data-dismiss="modal">
									Cancel
								</button>
								<%= f.submit "Save Store To Visit", class: "btn btn-primary" %>
							</div>
							<% end %>
						</div><!-- /.modal-content -->
					</div><!-- /.modal-dialog -->
				</div><!-- /.modal -->
				<td align="center"> <%= link_to(@storeToVisit, method: :delete, data: {confirm: 'Are you sure?'}) do  %> <i class="fa fa-trash fa-2x center"></i> <% end %> </td>
			</tr>
			<% end %>
			<% end %>

		</tbody>

	</table>
</div>

<script>
	$(document).ready(function() {
		var t = $('#itinerary').DataTable({
			"columnDefs" : [{
				"searchable" : false,
				"orderable" : false,
				"targets" : 0
			}],
			"order" : [[1, 'asc']]
		});

		t.on('order.dt search.dt', function() {
			t.column(0, {
				search : 'applied',
				order : 'applied'
			}).nodes().each(function(cell, i) {
				cell.innerHTML = i + 1;
			});
		}).draw();
	}); 
</script>

app/views/dashboard/_products.html.erb
<% @total = 0 %>
<div class="container" style="width: 100%; margin-top: 5%;">
	<table id="products" class="table table-striped" style="width: inherit;">
		<thead>
			<tr>
				<th>Name</th>
				<th>Store</th>
				<th>Price</th>
				<th>Qty</th>
				<th>Edit</th>
				<th>Done</th>
			</tr>
		</thead>
		<tbody>

			<% @products = Product.all %>

			<% @products.each do |product| %>
			<% productUser = User.find(product.user_id) %>
			<% store = Store.find(product.store_id) %>
			<% if productUser.id == current_user.id %>
			<tr>
				<td><%= product.name %></td>
				<td><%= store.name %></td>
				<td><%= number_to_currency(product.price) %></td>
				<td><%= product.quantity %></td>
				<% @total += product.price*product.quantity %>

				<td align="center"> <%= link_to(edit_product_path(product), 'data-target' => "#myProduct",
				'data-toggle' => 'modal') do  %> <i class="fa fa-pencil fa-2x center"></i> <% end %> </td>
				<div class="modal fade" id='<%= "myProduct" %>' tabindex="-1" role="dialog"
				aria-labelledby="myModalLabel" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
									&times;
								</button>
								<h4 class="modal-title" id="myModalLabel" align="left">Edit Product</h4>
							</div>
							<% @product = Product.find(product.id) %>
							<%= form_for @product do |f| %>
							<div class="modal-body">
								<%= render partial: 'products/edit', :locals => { f: f } %>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default" data-dismiss="modal">
									Cancel
								</button>
								<%= f.submit "Save Product", class: "btn btn-primary" %>
							</div>
							<% end %>
						</div><!-- /.modal-content -->
					</div><!-- /.modal-dialog -->
				</div><!-- /.modal -->
				<td align="center"> <%= link_to(@product, method: :delete, data: {confirm: 'Are you sure?'}) do  %> <i class="fa fa-check fa-2x center"></i> <% end %> </td>
			</tr>
			<% end %>
			<% end %>

		</tbody>

		<tfoot>
			<tr>
				<td><strong>Total:</strong></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td><strong><%= number_to_currency(@total) %></strong></td>
			</tr>
		</tfoot>

	</table>
</div>

<script>
	$(document).ready(function() {
		$('#products').DataTable();
	}); 
</script>

app/views/dashboard/home.html.erb
<script>
	function initialize() {
		var myCenter = new google.maps.LatLng(44.854602, -93.242045);
		var mapOptions = {
			center : myCenter,
			zoom : 17,
			minZoom : 17,
			mapTypeControl : true,
			mapTypeControlOptions : {
				style : google.maps.MapTypeControlStyle.HORIZONTAL_BAR
			},
			zoomControl : true,
			zoomControlOptions : {
				style : google.maps.ZoomControlStyle.SMALL
			},
			scaleControl : true,
			streetViewControl : true
		};
		var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
		
				// Add a Return to Center control that returns the user to the center of the Mall of America
		function HomeControl(controlDiv, map) {
			controlDiv.style.padding = '5px';
			var controlUI = document.createElement('div');
			controlUI.style.backgroundColor = 'yellow';
			controlUI.style.border = '1px solid';
			controlUI.style.cursor = 'pointer';
			controlUI.style.textAlign = 'center';
			controlUI.title = 'Set map to center of Mall of America';
			controlDiv.appendChild(controlUI);
			var controlText = document.createElement('div');
			controlText.style.fontFamily = 'Calibri,sans-serif';
			controlText.style.fontSize = '12px';
			controlText.style.paddingLeft = '4px';
			controlText.style.paddingRight = '4px';
			controlText.innerHTML = '<b>Center Map<b>'
			controlUI.appendChild(controlText);

			// Setup click-event listener: simply set the map to London
			google.maps.event.addDomListener(controlUI, 'click', function() {
				map.setCenter(myCenter)
			});
		};

		function ResetViewControl(controlDiv, map) {
			controlDiv.style.padding = '5px';
			var controlUI = document.createElement('div');
			controlUI.style.backgroundColor = 'aqua';
			controlUI.style.border = '1px solid';
			controlUI.style.cursor = 'pointer';
			controlUI.style.textAlign = 'center';
			controlUI.title = 'Reset view to default view of the Mall of America';
			controlDiv.appendChild(controlUI);
			var controlText = document.createElement('div');
			controlText.style.fontFamily = 'Calibri,sans-serif';
			controlText.style.fontSize = '12px';
			controlText.style.paddingLeft = '4px';
			controlText.style.paddingRight = '4px';
			controlText.innerHTML = '<b>Reset View<b>'
			controlUI.appendChild(controlText);

			// Setup click-event listener: simply set the map to the center of the Mall of America
			google.maps.event.addDomListener(controlUI, 'click', function() {
				map.setCenter(myCenter);
				map.setZoom(17);
			});
		};

		// Create a DIV to hold the control and call HomeControl()

		var homeControlDiv = document.createElement('div');
		var homeControl = new HomeControl(homeControlDiv, map);
		map.controls[google.maps.ControlPosition.RIGHT_CENTER].push(homeControlDiv);

		var resetViewControlDiv = document.createElement('div');
		var resetViewControl = new ResetViewControl(resetViewControlDiv, map);
		map.controls[google.maps.ControlPosition.LEFT_CENTER].push(resetViewControlDiv);
		
		google.maps.event.addListener(map, 'center_changed', function() {
			// Prevents map from being moved at max zoom level
			if (map.zoom == 17) {
				map.panTo(myCenter);
			}
		});

		var input = /** @type {HTMLInputElement} */(
			document.getElementById('pac-input'));

		map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);
		
		var defaultBounds = new google.maps.LatLngBounds(
		  new google.maps.LatLng(44.852373498451186, -93.24537630359652),
		  new google.maps.LatLng(44.85683041531407, -93.23871369640352));
		 

		var autocomplete = new google.maps.places.Autocomplete(input, {
			types : ['establishment'],
			bounds : defaultBounds,
			rankBy : 'DISTANCE'			
		});

		var infowindow = new google.maps.InfoWindow();
		var marker = new google.maps.Marker({
			map : map,
			anchorPoint : new google.maps.Point(0, -29)
		});

		google.maps.event.addListener(autocomplete, 'place_changed', function() {
			infowindow.close();
			marker.setVisible(false);
			var place = autocomplete.getPlace();
			if (!place.geometry) {
				window.alert("Autocomplete's returned place contains no geometry");
				return;
			}

			// If the place has a geometry, then present it on a map.
			if (autocomplete.getBounds().contains(place.geometry.location)) {
				if (place.geometry.viewport) {
					map.fitBounds(place.geometry.viewport);
				} else {
					map.setCenter(place.geometry.location);
					map.setZoom(20);
					// Why 20? Because it looks good.
				}

				marker.setIcon(/** @type {google.maps.Icon} */( {
					url : place.icon,
					size : new google.maps.Size(71, 71),
					origin : new google.maps.Point(0, 0),
					anchor : new google.maps.Point(17, 34),
					scaledSize : new google.maps.Size(25, 25)
				}));
				marker.setPosition(place.geometry.location);
				marker.setVisible(true);

				var address = '';
				if (place.address_components) {
					address = [(place.address_components[0] && place.address_components[0].short_name || ''), (place.address_components[1] && place.address_components[1].short_name || ''), (place.address_components[2] && place.address_components[2].short_name || '')].join(' ');
				}

				infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
				infowindow.open(map, marker);
			} else {
				var searchField = document.getElementById("pac-input");
				searchField.value = "";
				
				// window.alert(place.name + " could not be found within the bounds of the Mall of America" + map.getBounds().getNorthEast() + " " + map.getBounds().getSouthWest());
				// return;
			}
		});
		
		// google.maps.event.addListener(map, 'bounds_changed', function() {
			// var bounds = map.getBounds();
			// autocomplete.setBounds(bounds);
		// });
	}

</script>

<% provide(:title, 'Home') %>

<!-- Button trigger modal -->
<div align="center">

	<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#newStoreToVisit">
		New Store To Visit
	</button>

	<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#newProduct">
		New Product
	</button>

	<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#newComment">
		New Comment
	</button>

</div>

<!-- Modal -->
<div class="modal fade" id="newStoreToVisit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="myModalLabel">New Store To Visit</h4>
			</div>
			<div class="modal-body">
				<% @storeToVisit = StoreToVisit.new %>
				<%= render partial: "store_to_visits/form" %>
			</div>
		</div>
	</div>
</div>
<!-- Modal -->
<div class="modal fade" id="newComment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="myModalLabel">New Comment</h4>
			</div>
			<div class="modal-body">
				<% @comment = Comment.new %>
				<%= render partial: "comments/form" %>
			</div>
		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="newProduct" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="myModalLabel">New Product</h4>
			</div>
			<div class="modal-body">
				<% @product = Product.new %>
				<%= render partial: "products/form" %>
			</div>
		</div>
	</div>
</div>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-7">

			<div id="map-container">
				<input id="pac-input" class="controls" type="text" placeholder="Search Box">
				<div id="map-canvas"></div>
			</div>
		</div>

		<div class="col-md-5">
			<div style="margin-top: 25px; width: 100%;">
				<div align="center" class="accordion" id="accordion2">
					<div class="accordion-group">
						<div class="accordion-heading">
							<a class="accordion-toggle btn btn-primary" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne" style="width: 100%;">Store Itinerary</a>
						</div>
						<div id="collapseOne" class="accordion-body collapse">
							<div class="accordion-inner">
								<%= render partial: "dashboard/itinerary" %>
							</div>
						</div>
					</div>
					<div class="accordion-group">
						<div class="accordion-heading">
							<a class="accordion-toggle btn btn-primary" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo" style="width: 100%;">Shopping List</a>
						</div>
						<div id="collapseTwo" class="accordion-body collapse">
							<div class="accordion-inner">
								<%= render partial: "dashboard/products" %>
							</div>
						</div>
					</div>
					<div class="accordion-group">
						<div class="accordion-heading">
							<a class="accordion-toggle btn btn-primary" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree" style="width: 100%;">View Comments</a>
						</div>
						<div id="collapseThree" class="accordion-body collapse">
							<div class="accordion-inner">
								<%= render partial: "dashboard/comments" %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>