config/routes.rb
Rails.application.routes.draw do
  
  resources :store_to_visits
  resources :products
  resources :comments
  root 'dashboard#home'
  match '/home', to: 'dashboard#home', via: 'get'
  get 'stores/new'

  get 'stores/create'
  devise_for :users

end

app/models/store_to_visit.rb
class StoreToVisit < ActiveRecord::Base
  
end

app/controllers/store_to_visits_controller.rb
class StoreToVisitsController < ApplicationController
  before_action :set_store_to_visit, only: [:show, :edit, :update, :destroy]

  # GET /store_to_visits
  # GET /store_to_visits.json
  def index
    @store_to_visits = StoreToVisit.all
  end

  # GET /store_to_visits/1
  # GET /store_to_visits/1.json
  def show
  end

  # GET /store_to_visits/new
  def new
    @store_to_visit = StoreToVisit.new
  end

  # GET /store_to_visits/1/edit
  def edit
  end

  # POST /store_to_visits
  # POST /store_to_visits.json
  def create
    @store_to_visit = StoreToVisit.new(store_to_visit_params)

    respond_to do |format|
      if @store_to_visit.save
        format.html { redirect_to root_path, notice: 'Store to visit was successfully created.' }
        format.json { render :show, status: :created, location: @store_to_visit }
      else
        format.html { render :new }
        format.json { render json: @store_to_visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /store_to_visits/1
  # PATCH/PUT /store_to_visits/1.json
  def update
    respond_to do |format|
      if @store_to_visit.update(store_to_visit_params)
        format.html { redirect_to root_path, notice: 'Store to visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @store_to_visit }
      else
        format.html { render :edit }
        format.json { render json: @store_to_visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /store_to_visits/1
  # DELETE /store_to_visits/1.json
  def destroy
    @store_to_visit.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Store to visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store_to_visit
      @store_to_visit = StoreToVisit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_to_visit_params
      params.require(:store_to_visit).permit(:store_id, :user_id)
    end
end

app/helpers/store_to_visits_helper.rb
module StoreToVisitsHelper
end

app/views/store_to_visits/_edit.html.erb
<div align="center" class="field">
  <%= f.label :store_id %>
	<br>
	<%= f.select :store_id, @store_options %>
</div>
<%= f.hidden_field :user_id, value: current_user.id %>

app/views/store_to_visits/_form.html.erb
<%= form_for(@storeToVisit) do |f| %>
  <% if @storeToVisit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@storeToVisit.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @storeToVisit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div align="center" class="field">
  <%= f.label :store_id %>
	<br>
	<%= f.select :store_id, @store_options %>
</div>
<%= f.hidden_field :user_id, value: current_user.id %>

<div class="modal-footer actions">
	<button type="button" class="btn btn-default" data-dismiss="modal">
		Close
	</button>
	<%= f.submit class: "btn btn-primary"%>
</div>
<% end %>

app/views/store_to_visits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Store To Visits</h1>

<table>
  <thead>
    <tr>
      <th>Store</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @store_to_visits.each do |store_to_visit| %>
      <tr>
        <td><%= store_to_visit.store_id %></td>
        <td><%= store_to_visit.user_id %></td>
        <td><%= link_to 'Show', store_to_visit %></td>
        <td><%= link_to 'Edit', edit_store_to_visit_path(store_to_visit) %></td>
        <td><%= link_to 'Destroy', store_to_visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store to visit', new_store_to_visit_path %>

app/views/store_to_visits/new.html.erb
<h1>New Store To Visit</h1>

<%= render 'form' %>

<%= link_to 'Back', store_to_visits_path %>

app/views/store_to_visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Store:</strong>
  <%= @store_to_visit.store_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @store_to_visit.user_id %>
</p>

<%= link_to 'Edit', edit_store_to_visit_path(@store_to_visit) %> |
<%= link_to 'Back', store_to_visits_path %>